# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [14]:
# Import torch
import torch 
torch.__version__
# Create random tensor
random_tensor = torch.rand(size=(7,7))
random_tensor, random_tensor.dtype


(tensor([[6.0730e-01, 3.9461e-01, 1.7405e-01, 2.9578e-01, 8.0497e-01, 5.8977e-01,
          5.7842e-01],
         [8.8463e-01, 5.6178e-01, 6.0215e-01, 4.4014e-01, 5.8690e-01, 5.7900e-01,
          6.0887e-01],
         [4.2018e-01, 3.0749e-02, 1.4924e-01, 7.3892e-04, 1.4782e-02, 5.0690e-01,
          1.0481e-02],
         [1.6374e-01, 2.5082e-01, 4.9492e-01, 7.1095e-01, 8.5391e-01, 8.7949e-01,
          6.0849e-01],
         [1.8080e-01, 6.3038e-01, 1.5397e-02, 4.9866e-01, 7.1737e-01, 8.0517e-01,
          9.5550e-01],
         [5.3365e-01, 2.3573e-02, 5.7016e-01, 7.0261e-02, 2.6946e-01, 5.9628e-01,
          6.5195e-01],
         [7.6390e-01, 3.5097e-01, 5.4070e-01, 9.8958e-01, 6.8847e-01, 9.5838e-01,
          8.3346e-01]]),
 torch.float32)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [21]:
# Create another random tensor
another_random_tensor = torch.rand(size=(1,7))

another_random_tensor = another_random_tensor.T
# Perform matrix multiplication 

matrix_multiplication = random_tensor @ another_random_tensor
print(matrix_multiplication)
print(f"Shape of tensor: {matrix_multiplication.shape}")

tensor([[1.1939],
        [1.1061],
        [0.9868],
        [1.8999],
        [0.7716],
        [1.3174],
        [1.6353]])
Shape of tensor: torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [22]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor = torch.rand(size=(7,7))
another_random_tensor = torch.rand(size=(1,7))
another_random_tensor = another_random_tensor.T

# Matrix multiply tensors
matrix_multiplication = random_tensor @ another_random_tensor
print(matrix_multiplication)
print(f"Shape of tensor: {matrix_multiplication.shape}")


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])
Shape of tensor: torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [23]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [44]:
# Set random seed
torch.manual_seed(1234)
# Check if a GPU is available
if torch.backends.mps.is_available():
    device = torch.device("mps")  # Use the MPS device
    print("MPS backend is available")
else:
    device = torch.device("cpu")
    print("MPS is not available.")

# Create two random tensors on GPU
random_tensor_1 = torch.rand(size=(2,3)).to(device)
random_tensor_2 = torch.rand(size=(2,3)).to(device)
random_tensor_1, random_tensor_2



MPS backend is available


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='mps:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [48]:
# Perform matmul on tensor_A and tensor_B
answer = torch.matmul(random_tensor_1, random_tensor_2.T)
print(answer)
print(answer.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='mps:0')
torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [49]:
# Find max
max = torch.max(answer)

# Find min
min =torch.min(answer)

print(max,min)

tensor(0.5617, device='mps:0') tensor(0.3647, device='mps:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [51]:
# Find arg max
arg_max = torch.argmax(answer)

# Find arg min
arg_min = torch.argmin(answer)

arg_max, arg_min

(tensor(3, device='mps:0'), tensor(0, device='mps:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [52]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_random = torch.rand(size=(1,1,1,10))

# Remove single dimensions
tensor_squeeze = tensor_random.squeeze()

# Print out tensors and their shapes
print(tensor_random, tensor_random.shape)
print(tensor_squeeze, tensor_squeeze.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
